server:
  port: 9999
spring:
  rabbitmq:
    host: 192.168.5.208
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://192.168.5.208:${server.port}/eureka/