server:
  port: 31002
spring:
  application:
    name: hpdc-manager
  rabbitmq:
    host: 192.168.5.208
jwt:
  config:
    key: hpdc
eureka:
  client:
    service-url:
      defaultZone: http://192.168.5.208:31999/eureka/
  instance:
    prefer-ip-address: true
zuul:
  prefix: /api   # 访问网关路径的前缀（在映射路径的前面，一般用于区别开发的版本）
  retryable: true
  routes:
    hpdc-article:
      path: /article/**
      serviceId: hpdc-article
    hpdc-base:
      path: /base/**
      serviceId: hpdc-base
    hpdc-friend:
      path: /friend/**
      serviceId: hpdc-friend
    hpdc-gathering:
      path: /gathering/**
      serviceId: hpdc-gathering
    hpdc-qa:
      path: /qa/**
      serviceId: hpdc-qa
    hpdc-recruit:
      path: /recruit/**
      serviceId: hpdc-recruit
    hpdc-search:
      path: /search/**
      serviceId: hpdc-search
    hpdc-sms:
      path: /sms/**
      serviceId: hpdc-sms
    hpdc-spit:
      path: /spit/**
      serviceId: hpdc-spit
    hpdc-user:
      path: /user/**
      serviceId: hpdc-user
    hpdc-iface:
      path: /iface/**
      serviceId: hpdc-iface