server:
  port: 31008
spring:
  application:
    name: hpdc-search
  data:
    elasticsearch:
      cluster-nodes: 192.168.5.208:9300
eureka:
  client:
    service-url:
      defaultZone: http://192.168.5.208:31999/eureka/
  instance:
    prefer-ip-address: true