server:
  port: 31009
spring:
  application:
    name: hpdc-sms
  rabbitmq:
    host: 192.168.5.208
aliyun:
  sms:
    accessKeyId: ErMExBsffqTOvImy
    accessKeySecret: iFad6R8NJh7MNkoDmxKhjcbE6PhZiu
    template_code: SMS_182673659
    sign_name: HPDC短信验证码