server:
  port: 31005
spring:
  application:
    name: hpdc-spit
  data:
    mongodb:
      host: 192.168.5.208
      database: spitdb
  redis:
    host: 192.168.5.208
eureka:
  client:
    service-url:
      defaultZone: http://192.168.15.228:9999/eureka/
  instance:
    prefer-ip-address: true