server: 
  port: 31004
spring: 
  application:  
    name: hpdc-user #指定服务名
  datasource:  
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.208:3306/hpdc_user?characterEncoding=UTF8
    username: root
    password: oracle
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.5.208
  rabbitmq:
    host: 192.168.5.208
jwt:
  config:
    key: hpdc
eureka:
  client:
    service-url:
      defaultZone: http://192.168.5.208:31999/eureka/
  instance:
    prefer-ip-address: true